### ISSUE TITLE
Missing README.md file

### ISSUE THREAD

**Issue by obiwac** [NovAti0n/Portfolio#2]
@NovAti0n how am i supposed t o know hwat to read?

**Comment by drakeerv** [comment]
I also need this fixed STAT, ASAP, PRONTO, NOW

**Comment by NoaQuenon** [comment]
The problem is now fixed, thanks a lot for this issue @obiwac

**Comment by NoaQuenon** [comment]
> I also need this fixed STAT, ASAP, PRONTO, NOW

And I need you to calm down or I will be forced to ban you FOREVER :angry: 

Be careful @drakeerv, I'm watching you.

**Comment by obiwac** [comment]
Watch out @drakeerv , I think he's watching you 😳
