### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by drakeerv** [NovAti0n/Portfolio#4]
1. If I can't read how can I read the name of, "READMEIFYOUCANANDIFYOUCANTREADGOAWAY.md". I might mistakenly open thinking that I don't have to read it.
2. If I can't read how do I know what this is
3. Random repo button still not working
4. There is no LICENSE file so yeah
5. If I am blind I can't see the webpage
6. If I am deaf I can't listen to youtube

**Comment by drakeerv** [comment]
@NovAti0n

**Comment by NoaQuenon** [comment]
OK I'm gonna ban you if you don't leave me alone >:(

**Comment by drakeerv** [comment]
I'm just pointing out problems, are you going to fix them?

**Comment by NoaQuenon** [comment]
Does that answer your question?

**Comment by drakeerv** [comment]
No

**Comment by NoaQuenon** [comment]
Thanks for contacting NovAtion Inc.
